#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import commands

print commands.getoutput("rm -r /usr/share/JAMedia")
print commands.getoutput("rm /usr/share/applications/JAMedia.desktop")
print commands.getoutput("rm /usr/bin/jamedia")
print commands.getoutput("rm /usr/bin/jamedia_uninstall")
